spring.application.name=seniya_v2

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/seniya_db_v2

spring.datasource.username=root
spring.datasource.password=ckdgus@7719

jwt.secret=1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890
jwt.expiration=3600000
jwt.email-expiration-ms=180000

spring.main.allow-circular-references=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.config.import=optional:application-secret.properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=whdgus753@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=ture
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
file.upload-dir=/Users/jeonchanghyeon/upload/file
spring.mvc.static-path-pattern=/files/**
spring.web.resources.static-locations=file:/Users/jeonchanghyeon/upload/file

#Mybatis ??
# 1) XML ?? ?? ?? ?? (resources/mapper/*.xml ??? ?? ??? ??? ??)
mybatis.mapper-locations=classpath:mapper/*.xml
# 2) ?? ???? Entity ????? ??? ??? ?? (XML ???? ?? ???? ??? ? ?? ??)
mybatis.type-aliases-package=com.example.seniya_back.entity